# Generated by Django 5.0.6 on 2024-06-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_logs", "0003_topic_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
